[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
# Audio I/O and playback
cpal = "0.15"                    # Cross-platform audio I/O
symphonia = { version = "0.5", features = ["aac", "mp3", "isomp4", "alac"] }  # Audio decoding
rubato = "0.15"                  # Sample rate conversion
ringbuf = "0.4"                  # Lock-free audio buffers

# MIDI I/O
midir = "0.9"                    # Cross-platform MIDI I/O

# Utilities
anyhow = "1.0"                   # Error handling

# Serialization (M5)
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Audio export (M5)
hound = "3.5"                    # WAV encoding/decoding

# FFI bridge
flutter_rust_bridge = "2"        # Flutter-Rust bridge

# VST3 Plugin Hosting (M7)
# Note: VST3 hosting will require custom FFI bindings to VST3 SDK
# For now, adding supporting libraries for plugin infrastructure
lazy_static = "1.4"              # Plugin registry singleton
parking_lot = "0.12"             # Better mutexes for plugin thread safety
flate2 = "1.0"                   # Plugin state compression
base64 = "0.21"                  # Base64 encoding for plugin state
walkdir = "2.4"                  # Directory traversal for plugin scanning
